In [2]:
import numpy as np

Сначала решим систему, если матрица треугольная.

In [5]:
def solve_simple_system(A, b):
    def modify_system(i, b):
        for j in range(i):
            b[j] = b[j] - A[j][i]*answer[-1]
            #print b[j]
    answer = []
    row_number = A.shape[0]
    for i in range(row_number-1, -1, -1):
        answer.append(b[i]/A[i,i])
        modify_system(i, b)
    answer.reverse()
    return answer

In [6]:
A_simple = np.array([[2.0, 3.0],
                     [0.0, 3.0]])
b_simple = np.array([3.0, 1.0])

In [7]:
print solve_simple_system(A_simple, b_simple)

[1.0, 0.33333333333333331]


Видно, что работает нормально, теперь нужно написать функции, которые будут переводить любую систему к треугольному виду.

In [8]:
def to_simple(A, b):
    def non_zero(i):
        for k in range(A.shape[0])[i:]:
            if A[k][i] != 0:
                return k
    def change_places(m, n):
        copy = np.copy(A[m])
        A[m] = A[n]
        A[n] = copy
    column_number = A.shape[1]
    for i in range(column_number-1):
        nz = non_zero(i)
        change_places(i, nz)
        for j in range(column_number)[i+1:]:
            a_j_i = A[j][i]
            a_i_i = A[i][i]
            a_i = A[i]
            b_i = b[i]
            A[j] -= a_j_i/a_i_i*a_i
            b[j] -= a_j_i/a_i_i*b_i
            #print j, i, A[j][i]
    return A,b

In [9]:
A = np.array([[2.0, 3.0],
              [1.0, 3.0]])
b = np.array([3.0, 1.0])

In [10]:
print to_simple(A, b)

(array([[ 2. ,  3. ],
       [ 0. ,  1.5]]), array([ 3. , -0.5]))


Странные махинации сверху вроде "a_j_i = A[j][i]" нужны, чтобы в случае изменения матрицы всё равно всё посчиталось.

In [50]:
def solve_system(A,b):
    A1, b1 = to_simple(A, b)
    return solve_simple_system(A1, b1)

In [51]:
A_main = np.array([[70.0, 23.0, 31.0],
                    [42.0, 250.0, 66.0],
                    [73.0, 85.0, 287.0]])
b_main = np.array([100.0, 121.0, 12.0])

In [53]:
print solve_system(A_main, b_main)

[1.5654398657390658, 0.43712825353685331, -0.44567187220891091]


В в дальнейших вычислениях будет использоваться именно эта система.

Потому что для неё выполнено свойство диагонального преобладания.

Далее реализуем итеративный метод Зейделя.

In [81]:
def solve_by_zeidel(A, b):
    def devide_A (A):
        L1, D1, U1 = np.zeros(A.shape), np.zeros(A.shape), np.zeros(A.shape)
        for j in range(A.shape[0]):
            for k in range(A. shape[0]):
                if k == j:
                    D1[k][j] = A[k][j]
                if k > j:
                    L1[k][j] = A[k][j]
                if k < j:
                    U1[k][j] = A[k][j]
        #print A
        return L1, D1, U1
    L, D, U = devide_A(A)
    R = -1*np.dot(np.linalg.inv(L+D), U)
    F = np.dot(np.linalg.inv(L+D), b)
    x = np.zeros(A.shape[0])
    for i in range(100):
        x = np.dot(R, x) + F
    return x
        

In [86]:
def solve_by_variation(A, b):
    x = np.zeros(A.shape[0])
    for i in range(100):
        r = b - np.dot(A, x)
        x = x + np.dot(np.dot(A, r), r)/np.linalg.norm(np.dot(A, r))**2*r
    return x

In [77]:
A_main = np.array([[70.0, 23.0, 31.0],
                    [42.0, 250.0, 66.0],
                    [73.0, 85.0, 287.0]])
b_main = np.array([100.0, 121.0, 12.0])

In [78]:
print A_main

[[  70.   23.   31.]
 [  42.  250.   66.]
 [  73.   85.  287.]]


In [82]:
solve_by_zeidel(A_main, b_main)

array([ 1.51169875,  0.34769198, -0.44567187])

In [87]:
solve_by_variation(A_main, b_main)

array([ 1.51169875,  0.34769198, -0.44567187])

Видно, что все три метода дают правильный ответ.